In [3]:
#import functions
%pylab inline

# from MyUnits import *
from MyFunctions import *
from qutip import *

# from MyQubit import *
# import mpld3
import multiprocessing as mp
import itertools
import scipy.constants as sc
import time
import datetime


Populating the interactive namespace from numpy and matplotlib


In [142]:
N = 5
M = int(N/2)


a = tensor(qeye(N),destroy(2))
b = tensor(basis(N),qeye(2))
n = tensor(num(N,-M),qeye(2))


In [159]:
n

Quantum object: dims = [[5, 2], [5, 2]], shape = [10, 10], type = oper, isherm = True
Qobj data =
[[-2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  2.]]

In [181]:
create(10,-5)

ValueError: cannot convert float NaN to integer

Quantum object: dims = [[10], [10]], shape = [10, 10], type = oper, isherm = False
Qobj data =
[[ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [        nan  0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.                 nan  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.                 nan  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.                 nan  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   1.41421356  0.   

In [175]:
np*nm

ValueError: cannot convert float NaN to integer

Quantum object: dims = [[5, 2], [5, 2]], shape = [10, 10], type = oper, isherm = True
Qobj data =
[[ 0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j]
 [ 0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j]
 [ 0.00000000 +0.j  0.00000000 +0.j         nan+nanj  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j]
 [ 0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j         nan+nanj
   0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j]
 [ 0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j  0.00000000 +0.j
   0.00000000 +0.j  0.00000000 +0.j]
 [ 0.00000000 +0.

In [89]:
basis(10)

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 1.]
 [ 0.]]

In [154]:
identity(3)*qeye(3)

Quantum object: dims = [[3], [3]], shape = [3, 3], type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]